server:
  port: 80  # 또는 원하는 포트

spring:
  datasource:
    url: jdbc:mysql://123123:3306/dbname
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: ${DB_PASSWORD}


target:
  origins: https://123123